module.exports = [
  "111Skin",
  "37 Actives",
  "3Lab",
  "Aedes de Venustas",
  "Aerin Beauty",
  "Aesop",
  "African Botanics",
  "Alaïa Beauty",
  "Allies of Skin",
  "Amanda Lacey",
  "Amore Pacific",
  "Anja Rubik Fragrance",
  "Anya Hindmarch",
  "Apa Beauty",
  "Argentum Apothecary",
  "Aromatherapy Associates",
  "Artis Brush",
  "Atelier Cologne",
  "Aurelia Probiotic Skincare",
  "Avene",
  "Balmain Paris Hair Couture",
  "Bamford",
  "BBROWBAR",
  "beautyblender",
  "Beauty Works West",
  "Bella Freud Parfum",
  "BIOEFFECT",
  "Bobbi Brown",
  "Bodyism's Clean and Lean",
  "Bottega Veneta",
  "Buly 1803",
  "Bumble and bumble",
  "Burberry Beauty",
  "Byredo",
  "By Terry",
  "Caudalie",
  "Chantecaille",
  "Charlotte Tilbury",
  "Christian Louboutin Beauty",
  "Christophe Robin",
  "Cire Trudon",
  "Clarisonic",
  "Cleanse by Lauren Napier",
  "Colbert MD",
  "Color Me",
  "Color Wow",
  "Comme des Garcons Parfums",
  "Coqui Coqui",
  "D.S. & Durga",
  "David Mallett",
  "Davines",
  "Deborah Lippmann",
  "de Mamiel",
  "Derek Lam 10 Crosby",
  "DERMARCHÉ LABS",
  "Diana Vreeland Parfums",
  "Diane von Furstenberg",
  "Diptyque",
  "Dr. Barbara Sturm",
  "Dr. Dennis Gross Skincare",
  "Dr. Jackson's",
  "Dr Nigma Talib",
  "Dr Sebagh",
  "Earth Tu Face",
  "Edward Bess",
  "Elizabeth and James Nirvana",
  "Elizabeth Arden",
  "Ellis Brooklyn",
  "Ellis Faas",
  "Embryolisse",
  "Equi London",
  "Erno Laszlo",
  "Escentric Molecules",
  "Estelle & Thild",
  "Eve Lom",
  "Eve Snow",
  "Eyeko",
  "Foreo",
  "Fornasetti",
  "Frasco Mirrors",
  "Frederic Malle",
  "GHD",
  "Givenchy Beauty",
  "Globe-Trotter",
  "Goldfaden MD",
  "goop",
  "Grown Alchemist",
  "Hampton Sun",
  "Helmut Lang",
  "Hourglass",
  "Ila",
  "Ilia",
  "Illamasqua",
  "James Read",
  "JINsoon",
  "Jo Loves",
  "Joya",
  "Kahina Giving Beauty",
  "Kat Burki",
  "KENZOKI",
  "Kevyn Aucoin",
  "Kiehl's Since 1851",
  "Kilian",
  "Kjaer Weis",
  "Klorane",
  "KORA Organics by Miranda Kerr",
  "LAFCO",
  "La Mer",
  "Lancer",
  "Lancôme",
  "Lano - lips hands all over",
  "LashFood",
  "Laura Mercier",
  "Lauren B. Beauty",
  "Lavanila Laboratories",
  "Legology",
  "Le Labo",
  "Le Metier de Beaute",
  "Leonor Greyl",
  "Lilah B.",
  "Lipstick Queen",
  "Long by Valery Joseph",
  "M.i.h Jeans",
  "Maison Francis Kurkdjian",
  "Make Beauty",
  "Malin + Goetz",
  "Marc Jacobs Beauty",
  "Margaret Dabbs London",
  "Marie-Stella-Maris",
  "Marvis",
  "Mason Pearson",
  "Matter & Home",
  "Mauli Rituals",
  "May Lindstrom",
  "Michael Van Clarke",
  "Miller Harris",
  "Mio Skincare",
  "Miu Miu",
  "Moon Juice",
  "MZ Skin",
  "Nails inc",
  "Nannette de Gaspé",
  "NARS",
  "Natura Bissé",
  "Neat Nutrition",
  "Neom Organics",
  "NEST Fragrances",
  "Nomenclature",
  "Nurse Jamie",
  "NYDG Skincare",
  "Odin New York",
  "Omorovicza",
  "Onira Organics",
  "Oribe",
  "Original & Mineral",
  "Oskia",
  "Ouai Haircare",
  "Parfums DelRae",
  "Perricone MD",
  "Philip B",
  "PHILIP KINGSLEY",
  "Pommade Divine",
  "Prada",
  "PRTTY PEAUSHUN",
  "Purely Perfect",
  "Rahua",
  "REN Skincare",
  "REVERENCE DE BASTIEN",
  "RMS Beauty",
  "Rodin",
  "Roja Parfums",
  "ROSSANO FERRETTI Parma",
  "SACHAJUAN",
  "Santa Maria Novella",
  "Sarah Chapman",
  "Senteurs D'Orient",
  "Serge Lutens",
  "Shiseido",
  "SHOW Beauty",
  "Sisley - Paris",
  "Slip",
  "Smith & Cult",
  "Smythson",
  "Soleil Toujours",
  "SOVERAL",
  "Sunday Riley",
  "Surratt Beauty",
  "Susanne Kaufmann",
  "T3",
  "Tata Harper",
  "Tatcha",
  "Temptu",
  "TenOverTen",
  "The Beautiful Mind Series",
  "The Beauty Chef",
  "The Nue Co.",
  "The Perfumer's Story by Azzi Glasser",
  "The Super Elixir",
  "This Works",
  "Tom Daxon",
  "Tom Dixon",
  "Tom Ford Beauty",
  "Tracie Martyn",
  "Vernon François",
  "Verso",
  "Victoria Beckham Estée Lauder",
  "Vintner's Daughter",
  "Votary",
  "Wander Beauty",
  "Youth Corridor",
  "Yves Saint Laurent Beauty",
  "Zelens",
  "Zensation",
  "Ziip Beauty",
  "Colorless"
];
